
GET http://localhost:9080/airline/api/routes/2/tickets

###

GET http://localhost:9080/airline/api/routes/2/tickets/5

###

DELETE http://localhost:9080/airline/api/routes/2/tickets/4

###

POST http://localhost:9080/airline/api/routes/2/tickets/
Content-Type: application/json;

{
  "cost": 105.99,
  "dateTime": "2016-01-25T21:34:00",
  "routeId": 1
}

###

PUT http://localhost:9080/airline/api/routes/2/tickets/5
Content-Type: application/json;

{
  "cost": 99.99,
  "dateTime": "2016-01-26T21:34:00"
}
