// @no-cookie-jar
GET http://localhost:9080/airline/api/routes
Authorization: Basic ai5rb3dhbEBleGFtcGxlLmNvbTp1c2VydXNlcg==

###

// @no-cookie-jar
GET http://localhost:9080/airline/api/routes/2
Authorization: Basic ai5rb3dhbEBleGFtcGxlLmNvbTp1c2VydXNlcg==

###

// @no-cookie-jar
DELETE http://localhost:9080/airline/api/routes/1
Authorization: Basic ai5rb3dhbEBleGFtcGxlLmNvbTp1c2VydXNlcg==

###

// @no-cookie-jar
PUT http://localhost:9080/airline/api/routes/2
Authorization: Basic ai5rb3dhbEBleGFtcGxlLmNvbTp1c2VydXNlcg==
Content-Type: application/json;

{
  "destination": "Kraków",

  "startingPoint":"Praga",

  "duration": 120,

  "distance": 1000
}

###

// @no-cookie-jar
POST http://localhost:9080/airline/api/routes
Authorization: Basic ai5rb3dhbEBleGFtcGxlLmNvbTp1c2VydXNlcg==
Content-Type: application/json;

{
  "destination": "Berlin",

  "startingPoint":"Moskwa",


  "duration": 180,

  "distance": 1500
}

